# Generated by Django 3.2.12 on 2022-03-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='api.topic'),
        ),
        migrations.AlterField(
            model_name='child',
            name='child',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.topic'),
        ),
    ]
